---
language: python
python: "3.6"
notifications:
  email: false
addons:
  srcclr: true

install:
  # install Python packages
  - sudo pip install flake8 coveralls
  - sudo pip install -r requirements.txt

script:
  # create test user for unit tests
  - sudo useradd -p '$6$EeIWuA0rKjGSdc.f$.yZbGhuzpycWdK2PU.oA9cnJhrC5C68nel5TmSqMD7h9Nat1V.hRF/DIghIkUe8ryZMVqn6yLG9VvgxPNPTVy0' -M vagrant

  # run unit tests
  - export TEST_USERNAME=vagrant
  - export TEST_PASSWORD=vagrant
  - sudo make test

  # run unit tests with coverage for coveralls.io
  - sudo make coverage

  # run lint test
  - make lint

after_success:
  coveralls
